controller_list:
  - name: fake_left_manipulator_controller
    type: $(arg execution_type)
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
      - left_arm_joint_7
  - name: fake_right_manipulator_controller
    type: $(arg execution_type)
    joints:
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
      - right_arm_joint_7
initial:  # Define initial robot poses.
  - group: left_manipulator
    pose: stow
  - group: right_manipulator
    pose: stow